service: eventbridge-sqs
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

plugins: 
  - serverless-iam-roles-per-function

functions:
  hello:
    handler: functions/putEvents.putEvents
    events: 
      - http:
          path: /generate
          method: post
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "events:PutEvents"
        Resource: {"Fn::GetAtt" : [ "EventBus", "Arn" ]}
    
resources:
  Resources:
    EventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: QR_EVENT_BUS
  Outputs:
    EventBusName:
      Description: "Event Bus"
      Value: !Ref EventBus
